// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbrxivgrfizsehuofonu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpicnhpdmdyZml6c2VodW9mb251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDM3OTgsImV4cCI6MjA2MDQxOTc5OH0.sAUiup6uCiiPtSmygTL26fph51609_YlLerfOTgO-lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);